### ISSUE TITLE
Database Initialization

### ISSUE THREAD

**Issue by aherriot** [echenley/react-news#10]
When I use the firebase instance that you provided, it works.  After setting up my own firebase instance, and putting the security rules in from the readme file, I get an error when I launch the app.

```javascript
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.
```

Is there anything I should do to initialize the database?

**Comment by aherriot** [comment]
With an empty database, it redirects to the 404 page. I was able to strip out the contents of Posts.jsx, which allowed me to create a user, then make a post.  When I restore Posts.jsx, it functions properly.  That is why I thought that maybe the initial database state may be causing issues with the app.

**Comment by echenley** [comment]
Thanks for the report! This is now [fixed](https://github.com/echenley/react-news/commit/74d0fd1d9274367a2ebe8ebf106f29b869321490).
