### ISSUE TITLE
Cannot find module 'react-router/lib/HashHistory'

### ISSUE THREAD

**Issue by vitrum** [echenley/react-news#19]
I have an issue with HashHistory, when i run gulp get:

gulp-notify: [Compile Error] Cannot find module 'react-router/lib/HashHistory' from '/www/react/react-news/src/js'

I find one  issue post at  [react-router](https://github.com/rackt/react-router/issues/1592).

It look's like we need update the file '/src/js/routes.jsx'.

**Comment by echenley** [comment]
This was a react-router version issue. Should be fixed as of ea5711eb0915b7fa4fb7240f1024e97c35ae2a2c.
