### ISSUE TITLE
Use async actions instead of preEmit

### ISSUE THREAD

**Issue by Turbo87** [echenley/react-news#2]
First of all thanks for publishing this project, it helped me a lot in understanding more of the refluxjs concept!

When I looked at your actions file I was a bit surprised to find all the preEmit hooks there instead of using [async actions](https://github.com/spoike/refluxjs#asynchronous-actions). Did you do that on purpose, and if so then why?

**Comment by echenley** [comment]
Oh man, this is all new stuff since I was made React-News! There was a lot of discussion at the time about the best way to do action branching, and using preEmit hooks seemed like the consensus. It looks like Reflux has made a lot of improvements since. :P

**Comment by Turbo87** [comment]
Hehe okay. I expected something like that, just wanted to confirm. :+1:
