### ISSUE TITLE
add corejs for older browser compatibility

### ISSUE THREAD

**Issue by cjroth** [echenley/react-news#20]
this wasn't loading in many of the browsers that i tried, including chrome on my iphone and safari on mac os x because `object.assign` did not exist. adding corejs (from cnd) to the top of the index file solved it. would be great to include it through npm.

https://github.com/zloirock/core-js

**Comment by echenley** [comment]
Whoops, yeah looks like I forgot to re-add the babel runtime when I switched to webpack. Pushing a fix soon!

**Comment by cjroth** [comment]
Awesome, thanks :)
