### ISSUE TITLE
this.transitionTo breaks due to changes in react-router 1.0.x

### ISSUE THREAD

**Issue by rajaraodv** [echenley/react-news#21]
I saw errors in places where we are using transitionTo api. It used to be part of Navigation mixin but apparently they have changed it to History mixin. Also transitionTo no longer exists

please see:
Please see: https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md

**Comment by echenley** [comment]
@rajaraodv Thanks for the heads up!

**Comment by rajaraodv** [comment]
@echenley No worries, thanks for the great example app!
