### ISSUE TITLE
Can't create new users when using set-up described in Readme

### ISSUE THREAD

**Issue by juniorbird** [echenley/react-news#26]
I've tried following the instructions in the README, and am not successfully getting react-news to create new users after setting up my own Firebase DB.

I'm not familiar with Firebase and am probably missing something simple!

Steps to repro:

1. Create a new Firebase DB
2. Copy-and-paste Firebase config from README to Security & Rules in Firebase DB
3. Set Firebase url in constants.js to a new Firebase DB
1. Register as new user
1. Get "Something went wrong" error <br />
    ![screen shot 2016-05-07 at 4 36 45 pm](https://cloud.githubusercontent.com/assets/804191/15095628/befce352-1485-11e6-8ab4-f0415cae1fef.png)
1. Try what I think is the update format in the Simulator and get "No .write rule allowed the operation" <br />
    ![screen shot 2016-05-07 at 4 35 58 pm](https://cloud.githubusercontent.com/assets/804191/15095629/bf00c51c-1485-11e6-8bca-6257c46fdff6.png)

Is there another step? If so, I'm happy to screenshot doing that and submit a pull request for the README.

**Comment by echenley** [comment]
@juniorbird Hmm, That's interesting. I'm not exactly sure what's happening, but you might want to throw a `console.log` [here](https://github.com/echenley/react-news/blob/master/src/js/actions/Actions.js#L66) to see what the actual error code is. I haven't used the simulate feature, but I believe it's only set up to allow writes to `/users/:userId`, not `/users`. Once the user is created, I get the UID and [create the user profile](https://github.com/echenley/react-news/blob/master/src/js/actions/Actions.js#L72). Does this help?

**Comment by juniorbird** [comment]
That got it! The console.log pointed me in the right direction -- a small Firebase config thing. I'll submit a very tiny pull request with a README update. Thanks for your help!

**Comment by echenley** [comment]
@juniorbird That's great, thank you!
