### ISSUE TITLE
Firebase Structure

### ISSUE THREAD

**Issue by martin-ro** [echenley/react-news#29]
This might be a stupid question but what exactly is the "Firebase Structure" part in the README.md?
Sorry for my ignorance, it's the first time I'm using Firebase. I was able to deploy the App but now stuck.

I assume it is the database structure?

Cheers, Martin.

**Comment by echenley** [comment]
@martin-ro Exactly. It's how the data is stored in Firebase. It corresponds to how it's queried using the Firebase SDK, e.g. https://github.com/echenley/react-news/blob/master/src/js/actions/Actions.js#L12
