### ISSUE TITLE
Uncaught TypeError: Router.run is not a function

### ISSUE THREAD

**Issue by caseyyee** [echenley/react-news#3]
Having issues when trying to run the example.  I get this in the console:

app.js:258 Uncaught TypeError: Router.run is not a function

**Comment by mattgi** [comment]
+1

**Comment by mattgi** [comment]
if you update `react-router` to the latest version things start to work again. (it installed 0.10.2 for me on first go.. then I updated `package.json` and moved up to 0.12.0).

**Comment by echenley** [comment]
:+1: Hey guys, thanks for the heads up! Updated React-Router to v0.12.0 and implemented mattgi's fixes.
