### ISSUE TITLE
hostnameFromUrl

### ISSUE THREAD

**Issue by Guid75** [echenley/react-news#5]
gulp-notify: [Compile Error] Cannot find module '../mixins/hostnameFromUrl' from '/home/guillaume/tmp/react-news/src/scripts/components'

(archlinux 64bits)

post.jsx is expecting a file named ../mixins/hostnameFromUrl (line 14) but the real mixin is named host**N**ameFromUrl.js

**Comment by echenley** [comment]
Thanks for the heads up. This is now fixed.
