### ISSUE TITLE
Payload size can be decreased by replacing crypto by MD5

### ISSUE THREAD

**Issue by pandaiolo** [echenley/react-news#8]
I am playing with react-news and it's great, but the bundle is pretty big

Some things are unavoidable, like react or firebase, obviously

However, FYI I could reduce the package by importing `MD5` (caps) package, which is 9k, instead of `crypto` which is like 250k. Function usage is just `md5(string)` and returns the md5 hash.

Is crypto only used for generating md5 gravatar hash?

**Comment by echenley** [comment]
Good call. It is just being used for the gravatar hash. Would you want to submit a pull request with the updated dependencies? I can take care of it otherwise.

**Comment by pandaiolo** [comment]
Yep, submitting it right now
